from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle

OUT = Path('output/pdf'); OUT.mkdir(parents=True, exist_ok=True)
PDF = OUT / 'คู่มือการใช้งานและดูแลระบบเซิร์ฟเวอร์.pdf'
pdfmetrics.registerFont(TTFont('THSarabunPSK', r'C:\Users\Newsk\AppData\Local\Microsoft\Windows\Fonts\THSarabun.ttf'))
pdfmetrics.registerFont(TTFont('THSarabunPSKBold', r'C:\Users\Newsk\AppData\Local\Microsoft\Windows\Fonts\THSarabun Bold.ttf'))

s = getSampleStyleSheet()
s.add(ParagraphStyle(name='TitleThai', fontName='THSarabunPSKBold', fontSize=26, leading=32, alignment=TA_CENTER, textColor=colors.black, spaceAfter=7))
s.add(ParagraphStyle(name='CoverThai', fontName='THSarabunPSK', fontSize=17, leading=24, alignment=TA_CENTER, textColor=colors.black))
s.add(ParagraphStyle(name='H1', fontName='THSarabunPSKBold', fontSize=20, leading=25, textColor=colors.black, leftIndent=0, spaceBefore=8, spaceAfter=6))
s.add(ParagraphStyle(name='H2', fontName='THSarabunPSKBold', fontSize=17, leading=22, textColor=colors.black, leftIndent=.75*cm, spaceBefore=7, spaceAfter=4))
s.add(ParagraphStyle(name='Body', fontName='THSarabunPSK', fontSize=16, leading=21, alignment=TA_LEFT, textColor=colors.black, spaceAfter=5))
s.add(ParagraphStyle(name='List', fontName='THSarabunPSK', fontSize=16, leading=21, alignment=TA_LEFT, textColor=colors.black, leftIndent=1.5*cm, firstLineIndent=-.6*cm, spaceAfter=3))
s.add(ParagraphStyle(name='Small', fontName='THSarabunPSK', fontSize=13, leading=16, alignment=TA_LEFT, textColor=colors.black))
s.add(ParagraphStyle(name='SmallBold', fontName='THSarabunPSKBold', fontSize=13, leading=16, alignment=TA_LEFT, textColor=colors.black))
s.add(ParagraphStyle(name='Cmd', fontName='Courier', fontSize=7.8, leading=10.2, textColor=colors.black, borderColor=colors.black, borderWidth=.35, borderPadding=5, spaceAfter=6))
s.add(ParagraphStyle(name='Notice', fontName='THSarabunPSK', fontSize=15, leading=20, alignment=TA_LEFT, textColor=colors.black, borderColor=colors.black, borderWidth=.5, borderPadding=7, spaceBefore=5, spaceAfter=7))

def P(x, st='Body'): return Paragraph(x, s[st])
def T(headers, rows, widths):
    data = [[P(x, 'SmallBold') for x in headers]] + [[P(str(x), 'Small') for x in row] for row in rows]
    t = Table(data, colWidths=widths, repeatRows=1, hAlign='LEFT')
    t.setStyle(TableStyle([
        ('GRID',(0,0),(-1,-1),.35,colors.black), ('LINEBELOW',(0,0),(-1,0),.7,colors.black),
        ('VALIGN',(0,0),(-1,-1),'TOP'), ('LEFTPADDING',(0,0),(-1,-1),5), ('RIGHTPADDING',(0,0),(-1,-1),5),
        ('TOPPADDING',(0,0),(-1,-1),4), ('BOTTOMPADDING',(0,0),(-1,-1),4),
    ]))
    return t
def N(n, x): return P(f'{n} {x}', 'List')
def items(entries): return [N(f'{i}.', x) for i,x in enumerate(entries,1)]
def foot(c, d):
    c.saveState(); c.setStrokeColor(colors.black); c.setLineWidth(.25); c.line(1.8*cm,1.32*cm,A4[0]-1.8*cm,1.32*cm)
    c.setFont('THSarabunPSK',10); c.drawString(1.8*cm,.8*cm,'คู่มือการใช้งานและดูแลระบบเซิร์ฟเวอร์ เอกสารภายใน')
    c.drawRightString(A4[0]-1.8*cm,.8*cm,f'หน้า {d.page}'); c.restoreState()

story=[]
story += [Spacer(1,4*cm), P('คู่มือการใช้งานและดูแลระบบเซิร์ฟเวอร์','TitleThai'), P('สำหรับผู้ดูแลระบบและผู้ใช้งานต่อจากเดิม','CoverThai'), Spacer(1,1.1*cm), P('จัดทำจากเอกสารระบบที่มีอยู่ในโครงการ','CoverThai'), P('วันที่จัดทำ 14 กรกฎาคม 2569','CoverThai'), Spacer(1,1.5*cm), P('เอกสารฉบับนี้อธิบายโครงสร้าง วิธีเข้าถึง การใช้งาน การตรวจสอบ การบำรุงรักษา และการใช้งานระบบในภาษาที่ผู้เริ่มต้นใช้งานสามารถปฏิบัติตามได้','CoverThai'), Spacer(1,1*cm), P('ชั้นความลับ เอกสารภายในสำหรับผู้ดูแลระบบ','CoverThai'), PageBreak()]
story += [P('สารบัญ','H1'), P('1. วัตถุประสงค์และขอบเขต ........................................................................ 3'), P('2. ภาพรวมของระบบ ...................................................................................... 3'), P('3. วิธีเข้าระบบและสิทธิ์การใช้งาน .............................................................. 4'), P('4. โครงสร้างเครือข่ายและตำแหน่งของเครื่อง .............................................. 5'), P('5. รายละเอียดของแต่ละระบบ ........................................................................ 6'), P('6. ขั้นตอนปฏิบัติงานประจำวัน ...................................................................... 8'), P('7. การสำรองข้อมูลและการกู้คืน .................................................................... 9'), P('8. การตรวจสอบปัญหาเบื้องต้น .................................................................... 10'), P('9. การจัดการข้อมูลลับสำหรับผู้ดูแล ....................................................... 11'), P('10. รายการเริ่มงานสำหรับผู้ดูแลใหม่ ......................................................................... 12'), PageBreak()]
story += [P('1. วัตถุประสงค์และขอบเขต','H1'), P('1.1 เอกสารนี้จัดทำขึ้นเพื่อถ่ายทอดความรู้เกี่ยวกับระบบเซิร์ฟเวอร์ทั้งหมดให้ผู้รับผิดชอบคนถัดไปสามารถเข้าใจและดำเนินงานได้อย่างเป็นขั้นตอน โดยครอบคลุมเครื่องจริง ระบบเสมือน เครือข่าย ช่องทางเข้าถึง เว็บไซต์ ฐานข้อมูล และบริการที่เกี่ยวข้อง'), P('1.2 ข้อมูลอ้างอิงมาจากไฟล์ server_infrastructure.md, how_to_connect.md, CLOUDPANEL_VM_103.md และ credentials.md ในโครงการเดียวกัน ข้อมูลที่เอกสารต้นทางขัดกันจะถูกระบุเป็นรายการที่ต้องตรวจยืนยัน ไม่ควรคาดเดาค่าที่ถูกต้องเอง'), P('1.3 เอกสารนี้ไม่พิมพ์รหัสผ่านจริง ลิงก์เชิญ Token หรือ Secret จริงลงใน PDF เพื่อป้องกันการรั่วไหล ผู้ดูแลคนถัดไปต้องได้รับข้อมูลดังกล่าวผ่าน Password Manager หรือช่องทางที่ควบคุมสิทธิ์เท่านั้น','Notice')]
story += [P('2. ภาพรวมของระบบ','H1'), P('2.1 ระบบใช้ Proxmox VE เป็นศูนย์กลางควบคุมเครื่องเสมือน Proxmox ติดตั้งบนเครื่องจริงชื่อ Techniccom และเป็นจุดที่ใช้เปิด ปิด สำรองข้อมูล ดู Console และตรวจสอบทรัพยากรของทุกระบบย่อย'), T(['ประเภท','ชื่อหรือรหัส','หน้าที่','ช่องทางเข้าหลัก'],[
['Host','Techniccom','Proxmox VE 8.x บน Debian Bookworm ควบคุมระบบทั้งหมด','Proxmox Web UI และ SSH'],['LXC','CT 100 web-server','ให้บริการเว็บแอปหรือเว็บไซต์','Proxmox Console และ SSH'],['LXC','CT 102 database-server','เก็บ SQLite และข้อมูลสำรอง ยังไม่เป็นฐานข้อมูลแบบบริการเครือข่าย','Proxmox Console และ SSH'],['VM','VM 103 techniccom-cp','CloudPanel, Nginx, PHP FPM, MySQL และ SSH','CloudPanel, Console และ SSH'],['VM','VM 101 win10-light','Windows 10 Light สำหรับงานทั่วไป','Proxmox Console หรือ RDP']], [2.3*cm,3.2*cm,7.5*cm,4.2*cm]), PageBreak()]
story += [P('3. วิธีเข้าระบบและสิทธิ์การใช้งาน','H1'), P('3.1 การเข้าจากภายนอกให้ใช้ Tailscale ก่อนเสมอ Tailscale คือ VPN ที่เชื่อมเครื่องของผู้ดูแลเข้ากับเครือข่ายเดียวกับเซิร์ฟเวอร์โดยไม่ต้องเปิดพอร์ตบริหารจัดการสู่ Internet โดยตรง'), P('3.2 ขั้นตอนการเข้าจากภายนอก'), *items(['ติดตั้งโปรแกรม Tailscale จากเว็บไซต์ทางการบนเครื่องของผู้ดูแล','รับสิทธิ์เข้าร่วม Tailnet ด้วยบัญชีส่วนบุคคลที่ได้รับอนุมัติจากผู้ดูแล ไม่ใช้บัญชีร่วมกัน','เปิด Tailscale และตรวจว่าสถานะเป็น Connected','เปิดเบราว์เซอร์ไปที่ https://100.125.250.85:8006','เข้าสู่ระบบ Proxmox ด้วยบัญชีที่รับผ่าน Password Manager และเลือก Realm เป็น Linux PAM standard authentication','ตรวจสอบสถานะ Host, CT 100, CT 102, VM 103 และ VM 101 ก่อนดำเนินการใด ๆ']), P('3.3 การเข้าจากเครือข่ายในสถานที่เดียวกัน สามารถใช้ https://192.168.1.250:8006 หาก fallback IP ยังทำงานอยู่ เนื่องจากเครื่องหลักรับ IP แบบ DHCP จึงต้องตรวจสอบ IP ปัจจุบันเมื่อ URL นี้ใช้ไม่ได้'), P('3.4 เมื่อเข้า Proxmox สำเร็จ ให้เลือก Datacenter ตามด้วย Techniccom ในแถบซ้าย เลือก CT หรือ VM ที่ต้องการ จากนั้นใช้แท็บ Summary เพื่อตรวจสอบทรัพยากร ใช้แท็บ Console เพื่อเข้าหน้าจอ และใช้แท็บ Task เพื่อดูประวัติการทำงาน'), P('3.5 การใช้ SSH ให้เปิด Terminal หรือ PowerShell แล้วใช้รูปแบบคำสั่งต่อไปนี้ โดยรับชื่อบัญชีและรหัสผ่านหรือ SSH key จากทะเบียนข้อมูลลับเท่านั้น','H2'), P('ssh &lt;user&gt;@&lt;ip-or-hostname&gt;','Cmd'), PageBreak()]
story += [P('4. โครงสร้างเครือข่ายและตำแหน่งของเครื่อง','H1'), P('4.1 vmbr0 เป็นเครือข่ายหลัก เครื่องส่วนใหญ่รับ IP จาก Router ผ่าน DHCP จึงมีโอกาสเปลี่ยนเมื่อมีการรีสตาร์ต Router หรือหมดอายุ DHCP lease'), P('4.2 vmbr1 เป็นเครือข่ายภายในสำหรับเครื่องเสมือน ใช้เลข IP คงที่ในกลุ่ม 10.10.10.x เพื่อให้การสื่อสารระหว่าง Host และระบบย่อยไม่เปลี่ยนตาม Router'), T(['ระบบ','เครือข่ายหลัก','เครือข่ายภายใน','โดเมนหรือ VPN','ข้อสังเกต'],[
['Host Techniccom','DHCP และ fallback 192.168.1.250/24','10.10.10.1/24','Tailscale 100.125.250.85 และ techniccom-pve.pichyy.qzz.io','ศูนย์กลางของระบบ'],['CT 100','DHCP มีข้อมูลเดิม 192.168.1.113','10.10.10.100/24','aas.pichyy.qzz.io','เว็บแอป'],['CT 102','DHCP','10.10.10.102/24','ไม่มีโดเมนสาธารณะ','เก็บข้อมูล SQLite'],['VM 103','ข้อมูลล่าสุด 192.168.1.114/24','มีเอกสารระบุ 10.10.10.103/24','techniccom-cp.pichyy.qzz.io','ต้องตรวจ config จริง'],['VM 101','DHCP','ไม่มีข้อมูลระบุ','ไม่มี','Windows']], [2.3*cm,3.7*cm,3.0*cm,4.1*cm,3.1*cm]), P('4.3 Cloudflare Tunnel ทำงานบน Proxmox Host และมีไฟล์ตั้งค่าที่ /etc/cloudflared/config.yml หน้าที่ของ Tunnel คือส่งคำขอจากโดเมนสาธารณะไปยังบริการภายใน โดยเส้นทาง CloudPanel ที่บันทึกไว้ชี้ไปยัง https://192.168.1.114:8443 และตั้งค่า noTLSVerify ไว้'), P('4.4 ห้ามเปิดพอร์ต 8006 หรือ 22 ออกสู่ Internet โดยตรงโดยไม่มีการวิเคราะห์ firewall, MFA และนโยบายความปลอดภัย การเข้าระยะไกลสำหรับผู้ดูแลควรใช้ Tailscale เป็นหลัก'), PageBreak()]
story += [P('5. รายละเอียดของแต่ละระบบ','H1'), P('5.1 Proxmox Host Techniccom','H2'), T(['รายการ','รายละเอียด'],[['ระบบปฏิบัติการ','Debian Bookworm และ Proxmox VE 8.x'],['หน้าที่','เป็น Hypervisor จัดสรร CPU RAM Disk Network และควบคุม CT กับ VM'],['เครือข่าย','vmbr0 แบบ DHCP, fallback 192.168.1.250/24, vmbr1 10.10.10.1/24, Tailscale 100.125.250.85'],['คำสั่งตรวจสอบ','pveversion, qm list, pct list, df -h, ip a']], [4.2*cm,11.8*cm]), P('5.2 CT 100 web-server','H2'), T(['รายการ','รายละเอียด'],[['ระบบและทรัพยากร','Debian 12, 1 vCPU, RAM 4 GB, Swap 512 MB, Rootfs 20 GB บน pve-extra'],['เครือข่าย','net0 vmbr0 แบบ DHCP และ net1 vmbr1 10.10.10.100/24'],['หน้าที่','ให้บริการเว็บแอปหรือเว็บไซต์ผ่านโดเมน aas.pichyy.qzz.io'],['ข้อมูลร่วม','Host /mnt/pve-extra/shared-attendance-data/ เชื่อมไปที่ CT /home/tc-admin/shared-db-data/'],['ตรวจสอบ','systemctl --type=service --state=running, df -h, mount | grep shared']], [4.2*cm,11.8*cm]), P('5.3 CT 102 database-server','H2'), T(['รายการ','รายละเอียด'],[['ระบบและทรัพยากร','Debian 12, 1 vCPU, RAM 512 MB, Swap 512 MB, Rootfs 10 GB บน pve-extra'],['เครือข่าย','net0 vmbr0 แบบ DHCP และ net1 vmbr1 10.10.10.102/24'],['ข้อมูล','SQLite อยู่ที่ /mnt/database-backup/database.sqlite พร้อมไฟล์ -wal และ -shm'],['ข้อมูลร่วม','Host shared-attendance-data เชื่อมไปที่ CT /mnt/database-backup/'],['ขอบเขต','ยังไม่ได้ติดตั้งหรือให้บริการ MySQL หรือ PostgreSQL'],['โน้ตเดิม','/home/tc-admin/SERVER_NOTES.txt']], [4.2*cm,11.8*cm]), PageBreak()]
story += [P('5.4 VM 103 techniccom-cp','H2'), T(['รายการ','รายละเอียด'],[['ระบบ','Debian 12 Full VM, VM ID 103, auto start enabled'],['ทรัพยากร','2 vCPU และ Disk 32 GB บน pve-extra เอกสารขัดกันเรื่อง RAM ระหว่าง 4 GB และ 8 GB'],['เครือข่าย','ข้อมูลล่าสุดเป็น 192.168.1.114/24 gateway และ DNS 192.168.1.1 เอกสารอีกฉบับระบุ 10.10.10.103/24'],['บริการ','clp-nginx, clp-php-fpm, nginx, mysql MySQL 8.4 และ ssh'],['พอร์ต','80 HTTP, 443 HTTPS และ 8443 CloudPanel administration'],['URL','https://techniccom-cp.pichyy.qzz.io'],['คำสั่งบริหาร VM','qm status 103, qm start 103, qm shutdown 103, qm config 103, qm terminal 103']], [4.2*cm,11.8*cm]), P('5.5 วิธีใช้ CloudPanel','H2'), *items(['เข้า URL ของ CloudPanel ด้วยบัญชีผู้ดูแลจากทะเบียนข้อมูลลับ','ตรวจว่าสถานะ VM 103 เป็น Running ก่อนใช้งาน','สร้างเว็บไซต์โดยกำหนดโดเมน เจ้าของ PHP version และวิธีสำรองข้อมูลให้ชัดเจน','ตรวจบริการภายใน VM ด้วย sudo systemctl status clp-nginx clp-php-fpm nginx mysql ssh','ตรวจพอร์ตที่เปิดฟังด้วย sudo ss -ltnp','บันทึกทุกเว็บไซต์ที่สร้าง ชื่อโดเมน ผู้รับผิดชอบ และตำแหน่งข้อมูลลงทะเบียนระบบ']), P('5.6 VM 101 win10-light','H2'), P('ใช้ Windows 10 Tiny10 x64 23H2 มี 1 vCPU RAM 2 GB และ Disk 32 GB บน pve-extra รับ IP แบบ DHCP ให้ใช้ Proxmox Console เป็นวิธีแรกสำหรับเข้าหน้าจอ หากจะใช้ RDP ให้ตรวจ IP ปัจจุบัน การเปิด Remote Desktop และ firewall ใน Windows ก่อน'), PageBreak()]
story += [P('6. ขั้นตอนปฏิบัติงานประจำวัน','H1'), P('6.1 ก่อนปรับปรุงระบบ ให้ตรวจสอบว่ามี backup หรือ task ทำงานอยู่หรือไม่ ตรวจพื้นที่ disk บน Host และ Guest และบันทึกเวลาที่เริ่มปฏิบัติงาน'), P('6.2 ให้สร้าง backup หรือ snapshot ที่สามารถย้อนกลับได้ก่อนอัปเดต หรือเปลี่ยน configuration ที่มีผลต่อบริการ ห้ามอัปเดต Proxmox, CloudPanel, Nginx, PHP และฐานข้อมูลพร้อมกัน'), P('6.3 ลำดับเปิดระบบหลังไฟฟ้าดับ'), *items(['เปิด Proxmox Host และรอให้ Storage กับ Network พร้อม','ตรวจ CT 102 แล้วเริ่มการทำงาน','ตรวจ CT 100 แล้วเริ่มการทำงาน','ตรวจ VM 103 แล้วตรวจบริการเว็บและ CloudPanel','เริ่ม VM 101 เมื่อจำเป็น','ทดสอบการเข้าถึงบริการภายในและภายนอกทีละบริการ']), P('6.4 ลำดับปิดเพื่อบำรุงรักษา'), *items(['แจ้งผู้ใช้งานและตรวจการสำรองข้อมูล','ปิด VM 101','ปิดเว็บหรือ VM 103 และ CT 100 ตามแผนงานที่ได้รับอนุมัติ','ปิด CT 102 หลังยืนยันว่าไม่มีการเขียนข้อมูล','ปิด Proxmox Host เป็นลำดับสุดท้าย']), P('6.5 คำสั่งตรวจสอบบน Proxmox Host','H2'), P('qm list<br/>pct list<br/>qm status 103<br/>pct status 100<br/>pct status 102<br/>df -h<br/>journalctl -p warning -b','Cmd'), PageBreak()]
story += [P('7. การสำรองข้อมูลและการกู้คืน','H1'), P('7.1 เอกสารต้นทางยังไม่ระบุปลายทาง ตารางเวลา ระยะเก็บรักษา และผลการทดสอบกู้คืนของ backup ผู้ดูแลคนถัดไปต้องตรวจสอบข้อมูลนี้ใน Proxmox และบันทึกเป็นนโยบายก่อนเริ่มรับผิดชอบระบบเต็มรูปแบบ'), P('7.2 สำหรับ SQLite ไฟล์หลักอยู่ที่ /mnt/database-backup/database.sqlite และอาจมีไฟล์ database.sqlite-wal กับ database.sqlite-shm ไฟล์เหล่านี้เกี่ยวข้องกับ transaction ที่กำลังทำงาน จึงห้ามลบหรือคัดลอกแบบไม่เข้าใจสถานะการเขียนข้อมูล'), P('7.3 ขั้นตอนสำรองข้อมูลที่ปลอดภัย'), *items(['ตรวจว่าพื้นที่ปลายทางเพียงพอและสิทธิ์การเขียนถูกต้อง','ใช้วิธี backup ที่รองรับ SQLite หรือหยุดการเขียนข้อมูลตามขั้นตอนของแอปพลิเคชัน','ตรวจความสำเร็จของไฟล์สำรอง ขนาดไฟล์ วันที่ และ checksum เมื่อมี','เก็บ backup อย่างน้อยหนึ่งชุดนอกเครื่อง Host','บันทึกผู้ดำเนินการ เวลา และผลการตรวจสอบ']), P('7.4 การกู้คืนต้องทดสอบกับ VM หรือ CT ทดสอบก่อนเสมอ ห้าม restore ทับ production โดยตรง ให้สร้าง snapshot หรือสำเนาระบบก่อนทุกครั้ง'), PageBreak()]
story += [P('8. การตรวจสอบปัญหาเบื้องต้น','H1'), T(['อาการ','ลำดับตรวจสอบ','แนวทางปฏิบัติ'],[['เข้า Proxmox ไม่ได้','Tailscale Connected หรือไม่ URL ถูกต้องหรือไม่ เปิดจาก LAN ได้หรือไม่','ตรวจสิทธิ์ Tailscale และใช้ LAN fallback เมื่อมีเหตุจำเป็น'],['CT หรือ VM หยุดทำงาน','ตรวจ status, Task log, CPU, RAM และ Disk ของ Host','อ่าน error ก่อนสั่ง Start ห้ามสั่งซ้ำโดยไม่ทราบสาเหตุ'],['เว็บไซต์เปิดไม่ได้','ตรวจ DNS, Cloudflare, Tunnel, Guest, Nginx และ Application log','แยกสาเหตุทีละชั้นและแก้เฉพาะจุด'],['CloudPanel ใช้ไม่ได้','ตรวจ VM 103, port 8443, clp-nginx และ clp-php-fpm','เข้า Console หรือ SSH และตรวจ systemctl กับ journalctl'],['SQLite ใช้ไม่ได้','ตรวจ disk, ownership, file lock, WAL SHM และ bind mount','หยุดการเขียนก่อนสำรอง ห้ามลบไฟล์ประกอบโดยพลการ'],['IP เปลี่ยน','ตรวจ DHCP lease และ ip a ใน Console','ใช้ Tailscale หรือ static IP vmbr1 เป็นข้อมูลอ้างอิง']], [3.2*cm,6.9*cm,5.9*cm]), P('8.1 คำสั่งวินิจฉัยใน Linux Guest','H2'), P('ip a<br/>ip route<br/>ping -c 3 192.168.1.1<br/>df -h<br/>free -h<br/>systemctl --failed<br/>journalctl -xe --no-pager | tail -n 80<br/>sudo ss -ltnp','Cmd'), P('8.2 ให้หยุดและขอความช่วยเหลือทันทีเมื่อพบ disk I O error, filesystem เป็น read only, ข้อมูลสูญหาย, ต้อง restore, ต้องแก้ firewall หรือ Cloudflare policy หรือไม่มั่นใจว่าคำสั่งจะลบข้อมูลหรือรีบูต Host ได้'), PageBreak()]
story += [P('9. การจัดการข้อมูลลับสำหรับผู้ดูแล','H1'), P('9.1 ข้อมูลลับที่ต้องจัดส่งผ่าน Password Manager เท่านั้น ได้แก่ บัญชี Proxmox, SSH ของ Host และ CT, บัญชี CloudPanel, บัญชี Windows RDP, Tailscale Admin, Cloudflare, Domain DNS, Router ISP และบัญชีฐานข้อมูล'), P('9.2 รหัสผ่านที่เคยอยู่ในไฟล์ plaintext, แชต หรือ log ต้องถูกเปลี่ยนทันทีหลังผู้ดูแลคนถัดไปได้รับสิทธิ์ใหม่ และต้องเปิด MFA ในบริการที่รองรับ'), T(['รายการข้อมูลลับ','ที่เก็บที่กำหนด','ยืนยัน'],[['Proxmox URL บัญชี Realm รหัสผ่านและ MFA','Password Manager','□'],['Tailscale Admin ACL และอุปกรณ์ที่อนุมัติ','Password Manager และ Admin Console','□'],['CT 100 และ CT 102 SSH','Password Manager','□'],['VM 103 CloudPanel SSH และ MySQL','Password Manager','□'],['VM 101 Console และ RDP','Password Manager','□'],['Cloudflare Domain DNS Tunnel และ Billing','Password Manager','□'],['Router ISP และช่องทางกู้คืนบัญชี','Password Manager','□']], [6.4*cm,7.5*cm,2.1*cm]), P('9.3 ให้เพิกถอน invite link เก่าของ Tailscale ตรวจรายชื่ออุปกรณ์ใน Tailnet และลบอุปกรณ์ที่ไม่ใช้งาน สร้างบัญชีผู้ดูแลรายบุคคลและกำหนดสิทธิ์ขั้นต่ำที่จำเป็น'), PageBreak()]
story += [P('10. รายการเริ่มงานสำหรับผู้ดูแลใหม่','H1'), T(['รายการ','ผลที่ผู้ดูแลคนถัดไปต้องทำได้','ยืนยัน'],[['การเข้าถึง','ติดตั้ง Tailscale และเข้า Proxmox ด้วยบัญชีส่วนตัวได้','□'],['โครงสร้าง','อธิบายหน้าที่ Host, CT 100, CT 102, VM 103 และ VM 101 ได้','□'],['การปฏิบัติงาน','เปิด Console ดู Task log ดูทรัพยากร และเปิดปิด Guest อย่างปลอดภัยได้','□'],['CloudPanel','เข้าแผงควบคุมและตรวจ Nginx PHP MySQL ใน VM 103 ได้','□'],['ข้อมูล','ทราบตำแหน่ง SQLite และ shared bind mount','□'],['Backup','ตรวจ backup ล่าสุดและทำ restore test ในสภาพแวดล้อมทดสอบได้','□'],['ความปลอดภัย','รับ Secret ผ่าน Password Manager และ rotate รหัสเดิมแล้ว','□']], [3.2*cm,10.6*cm,2.2*cm]), P('10.1 ประเด็นที่ต้องตรวจยืนยันก่อนเริ่มดูแลระบบ','H2'), *items(['ตรวจค่า RAM จริงของ VM 103 ด้วย qm config 103 เนื่องจากเอกสารระบุทั้ง 4 GB และ 8 GB','ตรวจว่า VM 103 มีเฉพาะ 192.168.1.114/24 หรือมี net1 10.10.10.103/24 ด้วย โดยใช้ qm config 103 และ ip a ใน VM','ตรวจ IP DHCP ปัจจุบันของ CT 100 และ CT 102 และตรวจการตั้ง DHCP reservation ใน Router','ระบุปลายทาง ตารางเวลา และ retention ของ backup พร้อมผล restore test ล่าสุด','ระบุเจ้าของบัญชี Cloudflare Tailscale Domain DNS Router ISP และช่องทางกู้คืนบัญชี','รวบรวมรายชื่อเว็บไซต์ แอปพลิเคชัน Repository วิธี Deploy และเจ้าของข้อมูลของ CT 100 และ VM 103']), P('10.2 สรุป','H2'), P('ระบบมี Proxmox เป็นศูนย์กลาง Tailscale เป็นช่องทางผู้ดูแล Cloudflare Tunnel เป็นช่องทางบริการสาธารณะ CT 100 เป็นเว็บเซิร์ฟเวอร์ CT 102 เป็นที่เก็บ SQLite และข้อมูลสำรอง VM 103 เป็น CloudPanel และ VM 101 เป็น Windows สำหรับงานทั่วไป การเริ่มดูแลระบบอย่างปลอดภัยต้องยืนยันค่าที่ขัดกัน ทดสอบ backup และ rotate ข้อมูลลับทุกชุดก่อนผู้ดูแลคนถัดไปรับผิดชอบเต็มรูปแบบ')]

doc=SimpleDocTemplate(str(PDF),pagesize=A4,leftMargin=1.8*cm,rightMargin=1.8*cm,topMargin=1.7*cm,bottomMargin=1.8*cm,title='คู่มือการใช้งานและดูแลระบบเซิร์ฟเวอร์',author='Codex')
doc.build(story,onFirstPage=foot,onLaterPages=foot)
print(PDF)
